### ISSUE TITLE
Is the project abandoned?

### ISSUE THREAD

**Issue by mrkaban** [jimmyfm/krut#4]
Thank you very much for the program distributed under a free open license! Added a program to a Russian-language site about free software, here is the [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D0%BC%D1%83%D0%BB%D1%8C%D1%82%D0%B8%D0%BC%D0%B5%D0%B4%D0%B8%D0%B0/%D0%B7%D0%B0%D1%85%D0%B2%D0%B0%D1%82-%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0/krut-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B0-%D0%B4%D0%BB%D1%8F-%D1%81%D0%BD%D1%8F%D1%82%D0%B8%D1%8F-%D1%81%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%D0%BE%D0%B2-%D1%81-%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0.html).

Please do not drop the project, this is a very interesting program!

Will the program no longer be updated and new versions will no longer appear?

Will stable versions be published here or elsewhere?

**Comment by jimmyfm** [comment]
Thank you for sharing Krut around.

The project will continue being available, but I fear there will not be any new version. 

This is the original page of the project with all the version, if anything new is published will be published here:
https://sourceforge.net/projects/krut/
